on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0
      - run: |
          git config user.name Sebastian Peter
          git config user.email mail2sebastianpeter@gmail.com
          git checkout branch2
          git merge origin/banch1
          git push -u origin branch2
          gh --version
          gh auth login
          gh pr create --title "The bug is fixed" --body "Everything works again" --base main --head banch1
     # - name: pull-request-action
      #  uses: vsoch/pull-request-action@1.0.6
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # BRANCH_PREFIX: "branch2"
          #PULL_REQUEST_BRANCH: "main"
          #PULL_REQUEST_FROM_BRANCH: "branch2"


